version: '3'

services:
  mysql.monolito:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: eats
    volumes:
      - mysql.eats.monolito:/var/lib/mysql
volumes:
  mysql.eats.monolito:
